main:		main.cpp
		g++ -o out  main.cpp  -lGL  -lGLU  /usr/lib/libglut.so  -lm
		./out
main2:		main-myOwn-View-Point.cpp
		g++ -o out  main-myOwn-View-Point.cpp  -lGL  -lGLU  /usr/lib/libglut.so  -lm
		./out
sample:		sample.cpp
		g++ -o sample  sample.cpp  -lGL  -lGLU  /usr/lib/libglut.so  -lm
